import steveJobs from "./svg/steveJobs.svg"
import landingWave from "./svg/landingWave.svg"
import yourLogo from "./svg/yourLogo.svg"
import account from "./svg/account.svg"
import baloon from "./svg/baloon.svg"
import engine from "./svg/engine.svg"
import playbooksSelect from "./svg/playbooksSelect.svg"
import toDo from "./svg/toDo.svg"
import leave from "./svg/leave.svg"
import plus from "./svg/plus.svg"
import plusWhite from "./svg/plusWhite.svg"
import playbooks from "./svg/playbooks.svg"
import accountSelect from "./svg/accountSelect.svg"

export { steveJobs, landingWave, yourLogo, account, baloon, engine, playbooksSelect, toDo, leave, plus, plusWhite, playbooks, accountSelect }